name: Delete Branch Sandbox

on:
  delete

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Display branch name
        run: echo "${{ github.event.ref }}"
