name: Delete Branch Sandbox

on:
  delete

jobs:
  run:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Display Branch Name
        run: echo "${{ github.event.ref }}"
