name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment

jobs:
  simulate-deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print Refs
        run: |
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Ref: ${{ github.ref }}"

      - name: Print Commits
        run: git log --oneline

      - name: List Files
        run: ls -l

      - name: Simulate Deployment
        run: |
          echo "Simulating a deployment to ${{ inputs.environment }}."
          echo "Pretending to use URL: ${{ vars.URL }}"
