name: greeter

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions

      - name: Test
        run: deno test

      - name: Greet
        run: deno .github/actions/greeter/main.ts "${{ inputs.name }}"
