name: lib-test

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: lib

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions

      - name: Test
        run: deno test

  # Dependent projects:

  tools-bar:
    needs: test
    uses: ./.github/workflows/tools-bar-test.yml

  tools-foo:
    needs: test
    uses: ./.github/workflows/tools-foo-test.yml
