name: pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            core.startGroup("Prepare pull request");
              let prNumber = context.payload.pull_request.number;
              let prTitle = context.payload.pull_request.title;
              let prBody = context.payload.pull_request.body || "";

              if (prTitle.startsWith("staging-release-")) {
                prTitle = prTitle.replace("staging", "production");
                prBody = prBody.replace("staging", "production");
              } else {
                prTitle = `${prTitle} [production]`;
                prBody = `# staging -> production\nStaging PR: #${prNumber}\n${prBody}`;
              }
              
              core.info(JSON.stringify(context, null, 2));
              core.info(prTitle);
              core.info(prBody);
            core.endGroup();

            core.startGroup("Create pull request via API");
              await github.rest.pulls.create({
                base: "pull-request-poc",
                body: prBody,
                head: "${{ github.head_ref }}",
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: prTitle
              });
            core.endGroup();
