name: Ref Names

on:
  pull_requests:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Head Ref
        run: |
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Ref: ${{ github.ref }}"
