name: test-orchestrator

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        uses: ./.github/actions/orchestrator
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          pattern: "*-test.yml"
          pr: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
