name: test-orchestrator

on:
  pull_request:

defaults:
  run:
    working-directory: .github/actions/orchestrator

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .github/.tool-versions

      - name: Install
        run: deno install --frozen

      - name: Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.pull_request.number }}
        run: deno run --allow-env --allow-net main.ts
