name: bar-test

on:
  pull_request:
    branches: main
    paths: 
      - .github/workflows/tools-bar-test.yml
      - lib/** # Dependency
      - tools/bar/**
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    working-directory: tools/bar

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions

      - name: Test
        run: deno test
